### ISSUE TITLE
大佬能简单说一下该项目的架构吗？

### ISSUE THREAD

**Issue by stl714** [xuexiangjys/XUpdateService#5]
大佬能简单说下架构和所用到的技术吗？后端不是很了解想通过这个项目熟悉，希望能给个简单的说明

**Comment by wuuJiawei** [comment]
> 大佬能简单说下架构和所用到的技术吗？后端不是很了解想通过这个项目熟悉，希望能给个简单的说明

服务端：SpringBoot + tk.mybatis + druid
数据库：mysql
