### ISSUE TITLE
static resource

### ISSUE THREAD

**Issue by Yumore** [xuexiangjys/XUpdateService#7]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Dec 11 11:34:15 CST 2019
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by silentzone** [comment]
他这个只是个接口服务，不需要静态资源哦

**Comment by ziyouxiaozi** [comment]
我克隆下来运行也是这样，楼主怎么解决的？

**Comment by trdmm** [comment]
> 我克隆下来运行也是这样，楼主怎么解决的？

这个只有接口服务，文档说的打开`localhost:1111`没用。。。不过用postman请求各个接口，还是可以的

**Comment by xuexiangjys** [comment]
本项目只提供后台服务,后台管理界面请使用:
https://github.com/xuexiangjys/xupdate-management
